version: '3'
services:
  postgres:
    image: postgres:14.8-alpine
    ports:
        - "5442:5432"
    volumes:
        - ./postgres:/var/lib/postgresql/data
    environment:
        - POSTGRES_DB=memory
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_HOST_AUTH_METHOD=trust
        - ALLOW_IP_RANGE=0.0.0.0/0
        - PGDATA=/var/lib/postgresql/data/pgdata
  back:
    build: ./back
    ports:
        - "8080:8080"
    volumes:
        - ./back:/app
    environment:
        - POSTGRES_DB=memory
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_HOST=postgres
        - POSTGRES_PORT=5432
  front:
    build: ./front
    ports:
        - "3000:3000"
    volumes:
        - ./front:/app