# @name login
POST http://localhost:3001/api/web_app_data HTTP/1.1
Content-Type: application/json

{
  "token": "{hash from telegram}"
}


#############################

@authToken = {{login.response.body.token}}

# @name getQuiz
GET http://localhost:3001/api/quiz HTTP/1.1
Authorization: {{authToken}}


#############################

@authToken = {{login.response.body.token}}
@quizId = {{getQuiz.response.body.id}}
@quizSalt = {{getQuiz.response.body.salt}}
@quizAnswer = {{getQuiz.response.body.answers[0].id}}

POST http://localhost:3001/api/quiz HTTP/1.1
Authorization: {{authToken}}
Content-Type: application/json

{
  "id": "{{quizId}}",
  "salt": "{{quizSalt}}",
  "answer": "{{quizAnswer}}"
}
